3 feature 3 create and customize workout routines
CSC207-2022F-UofT/course-project-git_gud pull request #13
Opened 2022-11-14 17:33 UTC by turne142

2022-11-14 17:40 UTC, bdls-jamal requested changes
Coding Style:
- general structure is solid and readable
- helpful to have in line comments to assist with understanding what the code is doing
- 'UpdateHistory' has first letter capitalization, different from other methods in the same class(if this is intentional, let us know the reasoning and then it is okay)
- 'CompleteWorkout', 'RemoveExercise', 'AddExercise' same as above

2022-11-21 16:10 UTC, jhalaksaraogi commented on src/main/java/RoutineManagerController/WorkoutMenuController.java
> +        this.theView.addWorkoutSelectionDisplay(new WorkoutSelectionDisplay());
Since this constructor does have a few parameters, it might be a good idea to add Javadoc indicating what each of parameter is.

2022-11-21 16:18 UTC, jhalaksaraogi commented on src/main/java/RoutineManagerModel/Workout.java
> +    }
Great work on the Javadoc for the RoutineManagerModel package. The purpose of each of the three classes is clear. Each method's javadoc follows conventions and is very detailed.

2022-11-21 16:20 UTC, jhalaksaraogi commented on src/main/java/RoutineManagerController/WorkoutSelectionController.java
> +
Pl add Javadoc to the methods and the classes in the Controller package.

2022-11-21 16:21 UTC, jhalaksaraogi commented on src/main/java/RoutineManagerView/WorkoutSelection.java
> +}
Pl add Javadoc to the methods and the classes in the View package.

2022-11-22 02:48 UTC, bdls-jamal approved these changes, later dismissed
Code Styling:
- Changes were made to the notes in a previous comment.
- code is structured well and is readible

2022-11-22 03:52 UTC, absolute-xero7 approved these changes, later dismissed
The general coding structure is good.
Clean architecture is being followed.
Can use more javadoc to make the code easy to follow.

2022-11-28 19:13 UTC, turne142 commented
This Pull Request was merged to the main, however, the JavaDoc review is yet to be finished. We decided to merge right away to test our functionality. The JavaDoc will be finished TODAY.

2022-11-28 19:33 UTC, merged

2022-12-05 02:23 UTC, AHui156 reviewed
No testings have been done yet